spring:
  application:
    name: techfood

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/techfood
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8080
