apiVersion: apps/v1
kind: Deployment
metadata:
  name: techfood-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techfood-app
  template:
    metadata:
      labels:
        app: techfood-app
    spec:
      containers:
        - name: techfood-app
          image: pcantarelli/techfood
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/techfood"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
