apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          env:
            - name: POSTGRES_DB
              value: yourdbname
            - name: POSTGRES_USER
              value: youruser
            - name: POSTGRES_PASSWORD
              value: yourpassword
          ports:
            - containerPort: 5432
              name: postgres
