apiVersion: v1
kind: Service
metadata:
  name: kotlin-app-service
  labels:
    app: kotlin-app
spec:
  type: LoadBalancer # For minikube, use NodePort instead of LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kotlin-app
